version: '3.8'

services:
  postgres-btree:
    image: postgres:16-alpine
    container_name: fintech_postgres_btree
    command: >
      -c shared_buffers=128MB 
      -c autovacuum=off
    environment:
      POSTGRES_USER: fintech_admin
      POSTGRES_PASSWORD: secret_fin_pass
      POSTGRES_DB: fintech_analytics
    ports:
      - "5439:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    volumes:
      - pg_btree_data:/var/lib/postgresql/data

  clickhouse-lsm:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: fintech_clickhouse_lsm
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_lsm_data:/var/lib/clickhouse

volumes:
  pg_btree_data:
  ch_lsm_data:
