# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import orders_pb2 as proto_dot_orders__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrdersBulk = channel.unary_unary(
                '/orders.OrderGateway/GetOrdersBulk',
                request_serializer=proto_dot_orders__pb2.OrderRequest.SerializeToString,
                response_deserializer=proto_dot_orders__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrdersStream = channel.unary_stream(
                '/orders.OrderGateway/GetOrdersStream',
                request_serializer=proto_dot_orders__pb2.OrderRequest.SerializeToString,
                response_deserializer=proto_dot_orders__pb2.OrderRow.FromString,
                _registered_method=True)


class OrderGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrdersBulk(self, request, context):
        """Phase 1: Monolithic Bulk Data Retrieval RPC (Memory Intensive)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrdersStream(self, request, context):
        """Phase 2: High-Performance Server Streaming RPC (Memory Bounded)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrdersBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdersBulk,
                    request_deserializer=proto_dot_orders__pb2.OrderRequest.FromString,
                    response_serializer=proto_dot_orders__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrdersStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOrdersStream,
                    request_deserializer=proto_dot_orders__pb2.OrderRequest.FromString,
                    response_serializer=proto_dot_orders__pb2.OrderRow.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrderGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.OrderGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrdersBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrderGateway/GetOrdersBulk',
            proto_dot_orders__pb2.OrderRequest.SerializeToString,
            proto_dot_orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrdersStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/orders.OrderGateway/GetOrdersStream',
            proto_dot_orders__pb2.OrderRequest.SerializeToString,
            proto_dot_orders__pb2.OrderRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
