# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orders.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/orders.proto\x12\x06orders\"$\n\x0cOrderRequest\x12\x14\n\x0crecord_count\x18\x01 \x01(\x05\"\xb3\x01\n\x08OrderRow\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x12\n\norder_date\x18\x05 \x01(\t\x12\x16\n\x0epartition_year\x18\x06 \x01(\t\x12\x17\n\x0fpartition_month\x18\x07 \x01(\t\x12\x19\n\x11line_item_revenue\x18\x08 \x01(\x01\"1\n\rOrderResponse\x12 \n\x06orders\x18\x01 \x03(\x0b\x32\x10.orders.OrderRow2\x89\x01\n\x0cOrderGateway\x12<\n\rGetOrdersBulk\x12\x14.orders.OrderRequest\x1a\x15.orders.OrderResponse\x12;\n\x0fGetOrdersStream\x12\x14.orders.OrderRequest\x1a\x10.orders.OrderRow0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=30
  _globals['_ORDERREQUEST']._serialized_end=66
  _globals['_ORDERROW']._serialized_start=69
  _globals['_ORDERROW']._serialized_end=248
  _globals['_ORDERRESPONSE']._serialized_start=250
  _globals['_ORDERRESPONSE']._serialized_end=299
  _globals['_ORDERGATEWAY']._serialized_start=302
  _globals['_ORDERGATEWAY']._serialized_end=439
# @@protoc_insertion_point(module_scope)
